### ISSUE TITLE
[FEATURE] Update Finch dependency to 10.x

### ISSUE THREAD

**Issue by juddey** [akoutmos/prom_ex#111]
Hi Alexander

Just wondering if you know of any blockers OTOH to upgrading `finch` to the `0.10.x` version?  If not, happy to put through a PR if that's a change you'd like.

**Comment by juddey** [comment]
Dependency Resolution FYI:
```
Resolving Hex dependencies...

Failed to use "finch" (versions 0.10.0 and 0.10.1) because
  prom_ex (version 1.6.0) requires ~> 0.9.0
  mix.exs specifies ~> 0.10
```

**Comment by akoutmos** [comment]
That sounds good to me. Feel free to submit a PR! Thanks :)

**Comment by akoutmos** [comment]
Updated to 0.10.2. Thanks!

**Comment by juddey** [comment]
Thanks Alex!
