### ISSUE TITLE
[FEATURE] Configurable ETSCronFlusher interval

### ISSUE THREAD

**Issue by akasprzok** [akoutmos/prom_ex#123]
**Is your feature request related to a problem? Please describe.**
ETSCronFlusher is called frequently when scrape interval is greater than 7.5s.
This seems unnecessary, since the reductions will be performed at the scrape interval anyway.

**Describe the solution you would like to see**
By making the interval configurable, users can set it to a value greater than their scrape interval.
Then ETSCronFlusher only flushes when the endpoint isn't being scraped, which is its intended use, and is not called when the endpoint is being scraped regularly at an interval greater than 7.5s.

**How would you expect this feature to work**
Configure the [interval](https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/ets_cron_flusher.ex#L67) via the PromEx [config](https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/config.ex). For example,

```elixir
config :web_app, WebApp.PromEx,
    disabled: false,
    manual_metrics_start_delay: :no_delay,
    drop_metrics_groups: [],
    grafana: :disabled,
    metrics_server: :disabled,
    ets_flush_interval: 11_000
```

while retaining 7_500 ms as the default.

**Comment by akoutmos** [comment]
I added the implementation for this in #122. Thanks for the input!
