### ISSUE TITLE
[BUG] - prom_ex.dashboard.publish finch not loaded?

### ISSUE THREAD

**Issue by JowiM** [akoutmos/prom_ex#127]
This week we upgraded from 1.6 to 1.7.1. When running mix prom_ex.dashboard.publish both on our pipeline and local we are getting the following error. It looks as finch is not loaded. 

`
22:06:03.477 [error] GenServer Mix.Tasks.PromEx.Publish.Uploader terminating

** (ArgumentError) unknown registry: Backend.PromEx.GrafanaClient
(elixir 1.13.2) lib/registry.ex:1343: Registry.key_info!/1
(elixir 1.13.2) lib/registry.ex:576: Registry.lookup/2
(finch 0.10.2) lib/finch/pool_manager.ex:44: Finch.PoolManager.lookup_pool/2
(finch 0.10.2) lib/finch/pool_manager.ex:34: Finch.PoolManager.get_pool/2
(finch 0.10.2) lib/finch.ex:236: Finch.stream/5
(finch 0.10.2) lib/finch.ex:275: Finch.request/3
(prom_ex 1.7.0) lib/prom_ex/grafana_client.ex:155: PromEx.GrafanaClient.get_folder/2
(prom_ex 1.7.0) lib/prom_ex/dashboard_uploader.ex:143: PromEx.DashboardUploader.get_folder_id/3
Last message: {:continue, :upload_grafana_dashboards}
State: %{default_dashboard_opts: [otp_app: :backend], prom_ex_module: Backend.PromEx}
PromEx was unable to upload your dashboards to Grafana because:
{%ArgumentError{message: "unknown registry: Backend.PromEx.GrafanaClient"},
[
{Registry, :key_info!, 1, [file: 'lib/registry.ex', line: 1343]},
{Registry, :lookup, 2, [file: 'lib/registry.ex', line: 576]},
{Finch.PoolManager, :lookup_pool, 2, [file: 'lib/finch/pool_manager.ex', line: 44]},
{Finch.PoolManager, :get_pool, 2, [file: 'lib/finch/pool_manager.ex', line: 34]},
{Finch, :stream, 5, [file: 'lib/finch.ex', line: 236]},
{Finch, :request, 3, [file: 'lib/finch.ex', line: 275]},
{PromEx.GrafanaClient, :get_folder, 2, [file: 'lib/prom_ex/grafana_client.ex', line: 155]},
{PromEx.DashboardUploader, :get_folder_id, 3,
[file: 'lib/prom_ex/dashboard_uploader.ex', line: 143]}
]}
`

- Elixir version: 1.13.3
- Erlang/OTP version: 23.2.5
- Grafana version: 8.3.3
- Prometheus version: 2.26

**Comment by akoutmos** [comment]
Thanks for opening up the issue @JowiM. I'll take a look at this over the weekend and provide a fix
