### ISSUE TITLE
Integration with Telemetry

### ISSUE THREAD

**Issue by lkananowicz** [akoutmos/prom_ex#133]
Hi, this is more of question than issue. 

I wonder if there is a way to send events to PromEx which are already in Telemetry. I guess attaching additional Telemetry handler would be necessary, but how to send/forward those events to PromEx. 

Basically my question is would it be possible to resend events to PromEx without custom plugin implementation.

It is related to this question: https://github.com/TheRealReal/hackney_telemetry/issues/5

Thanks,
Leon

**Comment by akoutmos** [comment]
Hello and thanks for reaching out! I think there might be a bit of a misunderstanding here. Telemetry is merely a tool for exposing events via synchronous function dispatch. What attaches to those telemetry events becomes the responsibility of the library user.

PromEx takes on a lot of that responsibility by dealing with the execution and attaching-to of telemetry events and formats the events in a way that you can get those metrics into Prometheus. If you need to capture Prometheus metrics for any library that supports telemetry, you will need to write a PromEx plugin to support that library. In this particular instance, you will need to go through the supported telemetry events (https://github.com/TheRealReal/hackney_telemetry#telemetry-metrics) and find out what Prometheus data type fits that data point best and wrap that logic into a plugin that can be loaded by PromEx.

Hope that helps!

**Comment by akoutmos** [comment]
Awesome! Feel free to ping me on Elixir Slack if you need any help with the plugin :)
