### ISSUE TITLE
[BUG] Ecto plugin assumes Repo configuration is defined in the same application

### ISSUE THREAD

**Issue by DaniruKun** [akoutmos/prom_ex#138]
**Describe the bug**
Suppose we have an Elixir umbrella app, where we have an app `myapp`, and a `shared` app that contains things like shared dependencies, a shared `Ecto.Repo` etc. :
```
apps/
├── shared
└── myapp
```

When configuring the `PromEx.Plugins.Ecto` , we explicitly define the Repo we want:

```elixir
{Plugins.Ecto, [repos: [Shared.Repo]]}
```

However, the plugin assumes that we have the `Shared.Repo` defined in `myapp`, when actually we want to define it in `shared`.

The workaround is to define the config for `Shared.Repo` using `myapp` as the root key directly in the `myapp` application.

**To Reproduce**

1. Create an umbrella as described above
2. Configure an `Ecto.Repo` in `shared`, and define the config there using `config/3`
3. Configure the `PromEx` with the Ecto plugin as shown above
4. Start the app as an umbrella
5. Observe the issue

**Expected behavior**
Plugin correctly loads the config from `shared`

**Environment**

- Elixir version: 1.13.1-otp-24
- Erlang/OTP version: 24.2.1

**Additional context**
https://elixir-lang.slack.com/archives/C01NZ0FBFSR/p1650371145806739

**Comment by DaniruKun** [comment]
It seems that in my case even setting something like
```elixir
config :myapp, Shared.Repo, []
```

is enough to make it work.

**Comment by maxmarcon** [comment]
Exactly, I had the same problem and I came up with the same workaround
