### ISSUE TITLE
Release for latest telemetry support

### ISSUE THREAD

**Issue by anthonator** [akoutmos/prom_ex#164]
Would it be possible to cut a release so `telemetry` ~1.1 is officially supported?

**Comment by adamu** [comment]
Maybe `prom_ex` should actually require `~> 1.0`, not `~> 1.0.0`.

**Comment by adamu** [comment]
To add some detail, the latest release does not include #131, so it's not possible to add `prom_ex` (which depends on telemetry `~> 1.0.0`) to a project that is using telemetry `~> 1.1`

**Comment by gangstead** [comment]
#193 is merged in so the next release should allow newer versions of `telemetry`
