### ISSUE TITLE
Log error messages

### ISSUE THREAD

**Issue by tyhill2** [akoutmos/prom_ex#173]
Hello. I may not be understanding this correctly. How would I go about adding telemetry for the error message? I am currently using these plugins:

```
  @impl true
  def plugins do
    [
      # PromEx built in plugins
      Plugins.Application,
      Plugins.Beam,
      {Plugins.Phoenix, router: ScenarioManagerWeb.Router, endpoint: ScenarioManagerWeb.Endpoint},
      Plugins.Ecto,
      Plugins.PhoenixLiveView

      # Add your own PromEx metrics plugins
      # ScenarioManager.Users.PromExPlugin
    ]
  end
  ```
  
  And with those I can get the `status_code` and which `path` this 4XX or 5XX is coming back from, but it doesn't show the error message with it. Is there a way to achieve this? Or should I write my own plugin?

**Comment by akoutmos** [comment]
Hello there! I may be misunderstanding what you are saying, but what you are asking for fits better in your logs as opposed to metrics. With timeseries metrics, you do not want to store text data as that will greatly increase the cardinality of your timeseries data. What I would suggest instead, is use something like Sentry or Loki to capture error logs, and then use PromEx to have the time series metrics so you can see the points in time when errors occur, on what endpoints, and with what frequency.

Does that make sense?

**Comment by tyhill2** [comment]
Yes, I think that makes sense. I believe I am getting metrics and logging mixed/confused. I will look into Sentry and Loki. Is there a good way to get logs scraped by PromEx? Or does PromEx only scrape metrics?

**Comment by akoutmos** [comment]
PromEx at the moment is only concerned about metrics. Logs and traces are currently out of scope for this project. Closing this issue for now as it sounds like you are on the right path now :).
