### ISSUE TITLE
Ecto plugin not reporting for all Ecto Repos

### ISSUE THREAD

**Issue by feld** [akoutmos/prom_ex#180]
I have two Ecto repos on my application as one is for fetching (non-prometheus related) statistics data from a readonly database. Now the main application database's stats aren't showing up properly. Most of the stats appear to be in the /metrics output but some are only reporting the existence of one of the Repos

e.g.,

```
ethco_prom_ex_ecto_repo_init_status_info{database_host="tsdb1.int.foo.com",database_name="timescale",repo="App.TSRepo"} 1
```

**Comment by yordis** [comment]
Do you mind sharing your plugin configuration?

**Comment by yordis** [comment]
@feld please confirm this is not a duplicated of https://github.com/akoutmos/prom_ex/issues/180

**Comment by feld** [comment]
actually it appears to have been from incorrect order of applications in my supevisor. PromEx was starting after the Repo I wanted so it didn't catch it.
