### ISSUE TITLE
[FEATURE] support phoenix 1.7.0

### ISSUE THREAD

**Issue by glennr** [akoutmos/prom_ex#191]
I'm running into this when upgrading to Phoenix 1.7.0

Given this diff to mix.exs

```ellixr 
-      {:phoenix, "~> 1.6.15"},                                                                              
+      {:phoenix, "~> 1.7.0"},
-      {:phx_live_storybook, "~> 0.4.5"},
-      {:plug_cowboy, "~> 2.5"},
+      {:phoenix_storybook, "~> 0.5.0"},
+      {:plug_cowboy, "~> 2.6"},
```

I get this error

```
 % mix deps.get
Resolving Hex dependencies...
Resolution completed in 1.358s
Because prom_ex >= 1.5.0 depends on plug_cowboy ~> 2.5.1 and your app depends on plug_cowboy ~> 2.6, prom_ex >= 1.5.0 is forbidden.
So, because your app depends on prom_ex ~> 1.7.1, version solving failed.
```

I'm hoping a version bump works here:

- plug_cowboy now [requires Plug v1.14+ and Elixir v1.10+](https://github.com/elixir-plug/plug_cowboy/blob/master/CHANGELOG.md#v260)
- the plug bump [doesn't appear too onerous either]https://github.com/elixir-plug/plug/blob/main/CHANGELOG.md#v1140-2022-10-31)

**Comment by ivanhercaz** [comment]
This one is related with #182.

I am excited to enjoy with the support for Phoenix 1.7!
