### ISSUE TITLE
[BUG] Error message on app startup, if PromEx is started after the Endpoint

### ISSUE THREAD

**Issue by Ninigi** [akoutmos/prom_ex#194]
**Describe the bug**
```
RuntimeError: ** (RuntimeError) could not find persistent term for endpoint MyApp.Endpoint. Make sure your endpoint is started and note you cannot access endpoint functions at compile-time
```

**To Reproduce**

add `PromEx` to the children for the supervisor as described in current README

```elixir
children = [
  MyApp.PromEx,
  MyAppWeb.Endpoint,
  # ...
]
```

**Expected behavior**
Since `PromEx` relies on the Endpoint, the Endpoint should be started before `PromEx`.

**Environment**
Doesn't matter

**Additional context**
It is not going to bother you, until you have something like AppSignal giving you the same error message on every deploy.

**Comment by tmartin8080** [comment]
Closing, addressed in #195
