### ISSUE TITLE
[BUG] ETSCronFlusher high memory consumption and binaries leak

### ISSUE THREAD

**Issue by IIILSW** [akoutmos/prom_ex#198]
**Describe the bug**
We have registered high memory consumption by the ETSCronFlusher process heap  and large number of attached ref binaries.

In the course of our experiments, abandoning the use of Exporter and placing the process in hibernate after cleanup allowed us to reduce memory consumption under load by ~70mb

**To Reproduce**
Memory consumption increases steadily as the number of metrics and load increases (4k rps in our case)

**Expected behavior**

**Environment**

- Elixir version: 1.14.4
- Erlang/OTP version: 25.3
- Grafana version: -
- Prometheus version: -

**Additional context**
Created PRs in prom_ex and [telemetry_metrics_prometheus_core #55](https://github.com/beam-telemetry/telemetry_metrics_prometheus_core/pull/55)

**Comment by akoutmos** [comment]
This may fix the issue and will not require any changes to prometheus_core https://github.com/akoutmos/prom_ex/pull/200

**Comment by nthouliss** [comment]
Is it possible to get a published version with this patch? I had the same issue and this patch resolved it.

**Comment by weisslj** [comment]
@akoutmos same for us, we would really like to have a new version of `prom_ex` that includes this bug fix :pray:

**Comment by akoutmos** [comment]
Added this to my todo list for tomorrow! Sorry for the delay!
