### ISSUE TITLE
[BUG] Ecto dashboard is using incorrect value field for pool_size and timeout panels

### ISSUE THREAD

**Issue by onimsha** [akoutmos/prom_ex#222]
**Describe the bug**
In the Ecto dashboard JSON, it's using `/^Value$/` for the value fields. ([here](https://github.com/akoutmos/prom_ex/blob/master/priv/ecto.json.eex#L537) and [here](https://github.com/akoutmos/prom_ex/blob/master/priv/ecto.json.eex#L599)). This will render `No Data` in the generated dashboard the there's no such field with the `Value` string. 

**To Reproduce**

1. Enable the Ecto plugin.
2. Start my sample application
3. Check the Ecto Grafana dashboard

**Expected behavior**
It should use the correct field name, in this case the name of the metric.

**Comment by akoutmos** [comment]
Your fix has been merged and is available in 1.10.0! Thanks :)
