### ISSUE TITLE
[BUG] Sample dashboard screenshots link not working in docs

### ISSUE THREAD

**Issue by stefanluptak** [akoutmos/prom_ex#25]
When browsing https://hexdocs.pm/prom_ex/readme.html#available-plugins and I click the [Click here](https://hexdocs.pm/prom_ex/grafana-dashboards.html) link, it goes to error 404.

<img width="547" alt="Screenshot 2021-02-10 at 09 32 39" src="https://user-images.githubusercontent.com/23926/107484631-fda06580-6b82-11eb-8a80-9a45bafbfad6.png">

**Comment by akoutmos** [comment]
I'll put a gallery together today/tomorrow for each of the existing dashboards for that link to work. Thanks for finding that!

**Comment by akoutmos** [comment]
Just published a new version of the docs to Hex with all of the dashboard screenshots https://hexdocs.pm/prom_ex/all.html.

Thanks for opening up the issue!
