### ISSUE TITLE
[improvement] Make it explicit in docs that custom metrics require custom plugin

### ISSUE THREAD

**Issue by aloukissas** [akoutmos/prom_ex#36]
When defining our own custom telemetry events (e.g. "my_app.module.func.duration"), it's not entirely obvious from the docs that we need to write our own plugin to let prom_ex know about them and expose them to `/metrics`. What's more confusing, it's not clear that the definitions in `telemetry.ex` are for LiveDashboard, which `prom_ex` doesn't know of (or depend on).

**Comment by akoutmos** [comment]
Added some docs to talk about adding your own metrics and also talk about the differences between LiveDashboard and PromEx (3fb1598084cd470bd6119e1d80952fc69ce1e491). Thanks for the input!
