### ISSUE TITLE
Invalid dashboard_definition type

### ISSUE THREAD

**Issue by pallix** [akoutmos/prom_ex#40]
Hi there,

First thanks for creating this very useful library!

I have notice a small oddity: the code in `dashboard_uploader.ex` allow the user to specify extra dashboard option with the `dashboard_opts` variable. I personally used it like that:

```
        uid = dashboard_uid(source, path, deployment_env)

        {source, path, title: title, uid: uid}
```

The last line is the dashboard definition and `source` is the module, `path` the json file and so on. `dashboard_uid` implements my own uid function. This allows to reuse the same dashboard definition but generate one dashboard for each different deployment environment.

The options are read in the `handle_dashboard_render` function, with destructuring:

```
  defp handle_dashboard_render({otp_app, dashboard_relative_path}, default_assigns, prom_ex_module) do
    handle_dashboard_render({otp_app, dashboard_relative_path, []}, default_assigns, prom_ex_module)
  end

  defp handle_dashboard_render({otp_app, dashboard_relative_path, dashboard_opts}, default_assigns, prom_ex_module) do
```

This works but ultimately lead to a `dialyxir` error in my code because the type of `dashboard_definition` is too restrictive.
It is defined as `@type dashboard_definition() :: {atom(), String.t()}` in `prom_ex.ex`. It should be changed to take in account the non-mandatory options.

What do you think?

**Comment by akoutmos** [comment]
Good catch on the incorrect Typespec! I'll get a commit pushed up for that shortly.

As a side note, Grafana is a little weird with how it resolves and overwrites existing dashboards (which is why i implemented it the way I did unfortunately). If the name OR the UID collides, then Grafana will overwrite an existing dashboard hence why I dynamically generate the UID based on a few bits of information effectively taking that implicit burden off of the user.

Just something to be cautious about when naming your dashboards. You may need to dynamically generate the title for the dashboard and prefix/postfix the title with the environment. Something like "MyApp Phoenix Dashboard - DEV". Just a thought :).

**Comment by akoutmos** [comment]
Just pushed commit 45364f24baa98db0a3f44e99212bb3e34eab62c9 to address the typespec issue. Let me know if you have any issues using master instead of `1.0.1`. Else I'll close this issue in a couple days.

**Comment by pallix** [comment]
> Just something to be cautious about when naming your dashboards. You may need to dynamically generate the title for the dashboard and prefix/postfix the title with the environment.

Thank you very much for the information! I did prefix with the environment but I did not know it would have caused a problem otherwise :-)! 

I will check if I can remove the uuid, it would be good.

I will also check the type tomorrow and come back to you.

**Comment by akoutmos** [comment]
No problem :). Let me know how it works out for you!

**Comment by pallix** [comment]
It fixed the problem, thank you very much :)

**Comment by akoutmos** [comment]
Awesome! I'll close out the issue for now and cut a new release either today or tomorrow pending some other small things :). Thanks again!

**Comment by pallix** [comment]
P.S: having just a title such as `title: "#{deployment_env} - #{otp_app} BEAM dashboard"` without defining `dashboard_uid` is not enough. When changing `deployment_env`, it overrides the previous dashboard from another env.

**Comment by akoutmos** [comment]
Hrmm. I'll open this one up again and take a look as that shouldn't happen. Thanks for reporting back

**Comment by akoutmos** [comment]
I just realized that I haven't actually merged that fix in yet https://github.com/akoutmos/prom_ex/pull/32. It's been a busy couple of weeks and I forget to get that one in. Once it is in you should be good to go.

**Comment by pallix** [comment]
It explains the situation :-). Many thanks!

**Comment by akoutmos** [comment]
With https://github.com/akoutmos/prom_ex/pull/32 merged this should be resolved in the next release. Feel free to give the master branch a whirl again and reopen the issue if your problem persists.
