### ISSUE TITLE
[FEATURE] Enable Grafana Basic Auth

### ISSUE THREAD

**Issue by keatz55** [akoutmos/prom_ex#45]
# Problem
Many users setup Grafana and Prometheus via IaC workflows where generating, reading, and storing Grafana API tokens can be too much unnecessary overhead when compared with basic auth. Also, Grafana does not currently allow a way to initialize the app with default API tokens, but does allow initialization with basic auth credentials. As a result, this can make uploading Grafana dashboards via API token unnecessarily complex when compared with basic auth.

# Proposed Solution
Enable basic auth for uploading Grafana dashboards by no longer requiring `:auth_token` in `config.exs` file Grafana options:

```elixir
config :example, VMS.PromEx,
  grafana: [
    host: "http://admin:admin@localhost:3000" # <- No longer need auth_token because basic auth is in host url
  ]
```

## Possible Implementation:

- Update `PromEx.Config` to make `auth_token` no longer required
- Update `PromEx.GrafanaClient.Connection` to only add `Bearer #{auth_token}` if `not is_nil(auth_token)`
- Update `PromEx.GrafanaClient` to only add `Bearer #{auth_token}` header if `not is_nil(auth_token)`

**Comment by akoutmos** [comment]
Hey @keatz55, that's a really good idea. Sounds like your proposed implementation is all that is needed. Is this something you want to take on and make a PR for?

**Comment by keatz55** [comment]
@akoutmos Thanks for the response. I'll jump on it. PR incoming.

**Comment by akoutmos** [comment]
Awesome! Thanks :)
