### ISSUE TITLE
Sharing a grafana folder between multiple applications

### ISSUE THREAD

**Issue by pallix** [akoutmos/prom_ex#48]
**Is your feature request related to a problem? Please describe.**
I'm uploading dashboards from several applications in a folder with the same name. This triggers this error:
```
** (CaseClauseError) no case clause matching: {:ok, %Finch.Response{body: "{\"message\":\"A folder or dashboard in the general folder with the same name already exists\"}", headers: [{"cache-control", "no-cache"}, {"content-type", "application/json"}, {"expires", "-1"}, {"pragma", "no-cache"}, {"x-content-type-options", "nosniff"}, {"x-frame-options", "deny"}, {"x-xss-protection", "1; mode=block"}, {"date", "Thu, 15 Apr 2021 14:25:41 GMT"}, {"content-length", "91"}], status: 400}}
```

**Describe the solution you would like to see**
I would like to group my dashboards according to their deployment environment. Each environment contains different applications. This is currently not possible because of the logic implemented in `__grafana_folder_ui__`. The assumption in the function is that each application has one folder for itself.

**How would you expect this feature to work**
Maybe allow to overwrite `grafana_folder_ui`?

**Comment by akoutmos** [comment]
Thanks for opening up the issue. That totally makes sense. Would it be helpful if I expose a config field for providing your own UID for the folder? That way you can provide the ID else I can make it for you? The Grafana API is a bit weird with the names+ids of dashboards and folders hence why I've had to put in place the md5 hashes and stuff like that.

Let me know if the proposed solution works for you. Thanks!

**Comment by pallix** [comment]
And thanks for the quick feedback :-). A config field along `folder_name` for example? Advantage is that it's simple but I'm not sure which value I would need to put in it? As far as I know you can't do calculate much in config files.

For the moment I have, for example in `config/dev.exs`:

```
    folder_name: System.get_env("DEPLOYMENT_ENV") || "dev",
```

so it would look like this:

```
granafa:[
   [...]
    folder_name: System.get_env("DEPLOYMENT_ENV") || "dev",
   folder_uid: ???
]
```

where `???` is maybe `(System.get_env("DEPLOYMENT_ENV") || "dev") <> "heregeneratesomethingunique"`.

What do you think?

**Comment by akoutmos** [comment]
The UID can be any 40 character string the uniquely identifies the folder. Currently I calculate that for you under the hood so if I change how I calculate that value it will be a breaking change for all existing deployments. Off loading that to config (like how I proposed) would allow you to get around the current limitation without introducing a breaking change. Thoughts?

**Comment by pallix** [comment]
Ok then something like:

```
grafana: [
 foldler_uid: String.pad_trailing(System.get_env("DEPLOYMENT_ENV"), 42, "0")
]
```

should work. It's good for me. If you can create a branch, I can test it on my setup and give you feedback.

**Comment by akoutmos** [comment]
Sounds good. I'll try and put something together mid next week for this :).

**Comment by pallix** [comment]
awesome, thank you!

**Comment by akoutmos** [comment]
I haven't forgotten about this. I have a fix in the works....but need to do some thorough testing to ensure that I don't break backwards comparability for existing PromEx users.

**Comment by akoutmos** [comment]
Could you give this branch a test drive and see if it resolves your issue? I tested this out with the example app in the repo and it looked like it fixed the issue that I was able to repro...but another real world test would be much appreciated :).

https://github.com/akoutmos/prom_ex/pull/56

**Comment by pallix** [comment]
Thanks for getting back to this.

I got the following error when starting the app, even when `upload_dashboards_on_start: false`:

```

May 03 12:10:58 hostname app-name[26355]:  [::my_app, :readout, :in, :count]} has failed and has been detached. Class=:error
May 03 12:10:58 hostname app-name[26355]: Reason={:badkey, :error, %{serial: 100059}}
May 03 12:10:58 hostname app-name[26355]: Stacktrace=[
                                                             May 03 12:10:58 hostname app-name[26355]:   {Observability.Events, :drop_error_and_resent, 1,
                                                             May 03 12:10:58 hostname app-name[26355]:    [file: 'lib/observability/events.ex', line: 56]},
                                                             May 03 12:10:58 hostname app-name[26355]:   {Telemetry.Metrics, :"-keep_fun/2-fun-0-", 2,
                                                             May 03 12:10:58 hostname app-name[26355]:    [file: 'lib/telemetry_metrics.ex', line: 633]},
                                                             May 03 12:10:58 hostname app-name[26355]:   {TelemetryMetricsPrometheus.Core.Counter, :handle_event, 4,
                                                             May 03 12:10:58 hostname app-name[26355]:    [file: 'lib/core/counter.ex', line: 54]},
                                                             May 03 12:10:58 hostname app-name[26355]:   {:telemetry, :"-execute/3-fun-0-", 4,
                                                             May 03 12:10:58 hostname app-name[26355]:    [file: '/home/user/projects/app/deps/telemetry/src/telemetry.erl', line: 135]},
                                                             May 03 12:10:58 hostname app-name[26355]:   {:lists, :foreach, 2, [file: 'lists.erl', line: 1338]},
                                                             May 03 12:10:58 hostname app-name[26355]:   {MyApp.Receiver, :in_measure, 1,
                                                             May 03 12:10:58 hostname app-name[26355]:    [file: 'lib/my_app/receiver.ex', line: 110]},
                                                             May 03 12:10:58 hostname app-name[26355]:   {MyApp.Receiver, :process_encoded_message, 2,
                                                             May 03 12:10:58 hostname app-name[26355]:    [file: 'lib/my_app/receiver.ex', line: 49]},
                                                             May 03 12:10:58 hostname app-name[26355]:   {MyApp.Receiver, :handle_info, 2,
                                                             May 03 12:10:58 hostname app-name[26355]:    [file: 'lib/my_app/receiver.ex', line: 41]}
                                                             
```

The connection to the grafana is currently not available from this machine but since I disabled the upload with `false` it should work but does not. `Serial` is one of the metadata I used in the events.

**Comment by pallix** [comment]
I tested on a few apps locally and uploaded to a remote server and it works fine.

**Comment by akoutmos** [comment]
Sounds good! I'll add some tests around this to the suite and merge shortly afterwards. Thanks for giving it a test drive :).

**Comment by pallix** [comment]
I have a problem when uploading a new dashboard:

```
PromEx.DashboardUploader failed to upload /home/user/projects/app/_build/dev/lib/observability/priv/dashboards/msgs_latency.json.eex to Grafana: :not_found
```

Could it be related to this issue? The file is there.

**Comment by pallix** [comment]
I have a problem related to this issue: when uploading the app dashboards to different folders (one for each `env`), a last write win situation occurs. The dashboards from the previous folder are removed and only the latest folder has the dashboards.

This occurs even with my own dashboard_uid having this string `"#{env}:#{otp_app_name}:#{module_name}:#{dashboard_otp_app_name}:#{dashboard_path}"`

**Comment by pallix** [comment]
The problem above does not occur if I put the `env` in the title, but since I already distinguished the env with the folder, I didn't want to put the env name in the title.

**Comment by akoutmos** [comment]
Can you open up a new issue for that. Grafana is a bit weird with the name/uid resolution so while it is different than the problem in this issue, def something I'll need to look into. Thanks!
