### ISSUE TITLE
[BUG] When starting an isolated metrics sever, it keeps the plug one too

### ISSUE THREAD

**Issue by xaviRodri** [akoutmos/prom_ex#50]
**Describe the bug**
When using a Phx appliaction, with its own `endpoint.ex` and so, we already have the prom_ex `/metrics` endpoint in the same `MyApp.Endpoint`. This happens because we add the `PromEx.Plug` to the `Endpoint`.
If we want this server to be in another port, first thing we will try is to use this `metrics_server` config where we can specify another route for the metrics. The problem is that both are working at the same time, but if we set this isolated metrics server is because we don't want the first one.

**To Reproduce**

1. Create a simple Phoenix App
2. Add prom_ex and its config
3. Add the PromEx.Plug to the Endpoint
4. Add the `metrics_server` config and set it to another port
5. Start the application and see that `/metrics` is available in both ports

**Expected behavior**
The first `/metrics` from the Endpoint should be deactivated as we are setting another one.

**Environment**

- Elixir version: 1.11.4
- Erlang/OTP version: 23
- Grafana version: 7.5.4
- Prometheus version: 2.26.0

**Additional context**
Maybe some people wants both to be working at the same time. 
So adding a `:disabled` option like we have for the grafana config would solve the problem.

**Comment by akoutmos** [comment]
The `metrics_server` config is an optional config where you can user that *instead* of the plug. If I read your issue correctly it sounds like all you need to do is remove the PromEx plug entry in `endpoint.ex` and the standalone metrics server will be the only thing hosting metrics.

**Comment by xaviRodri** [comment]
True fact.. sorry for the silly question!
