### ISSUE TITLE
[BUG] ** (ArgumentError) cannot convert the given list to a string.

### ISSUE THREAD

**Issue by zmagajna** [akoutmos/prom_ex#69]
**Describe the bug**
I have a problem plugging PromEx on my umbrella project, application is using GraphQL and ecto on the different applications. I have set up PromEx as a seperate application just to test it out for my case, set up in the config metrics server and exposing it to the prometheus. but when the call is made to the exposed endpoint I get an error:

```
15:00:15.548 [error] GenServer Monitoring.PromEx.ETSCronFlusher terminating
** (ArgumentError) cannot convert the given list to a string.
To be converted to a string, a list must either be empty or only
contain the following elements:
  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements
Please check the given list or call inspect/1 to get the list representation, got:
[schema: GameDataAPIWeb.API.Schema, socket: GameDataAPIWeb.UserSocket, json_decoder: Jason, interface: :simple]
    (elixir 1.10.4) lib/list.ex:925: List.to_string/1
    (telemetry_metrics_prometheus_core 1.0.1) lib/core/exporter.ex:112: TelemetryMetricsPrometheus.Core.Exporter.escape/1
    (telemetry_metrics_prometheus_core 1.0.1) lib/core/exporter.ex:98: anonymous fn/1 in TelemetryMetricsPrometheus.Core.Exporter.format_labels/1
    (elixir 1.10.4) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
    (stdlib 3.13.2) maps.erl:233: :maps.fold_1/3
    (elixir 1.10.4) lib/enum.ex:2127: Enum.map/2
    (telemetry_metrics_prometheus_core 1.0.1) lib/core/exporter.ex:98: TelemetryMetricsPrometheus.Core.Exporter.format_labels/1
    (telemetry_metrics_prometheus_core 1.0.1) lib/core/exporter.ex:87: anonymous fn/2 in TelemetryMetricsPrometheus.Core.Exporter.format_standard/2
Last message: :flush_ets
```

Where the keyword list is a setup for the forward in phoenix router. Could someone help me debug what the problem with this could be?
The example that I was working of: https://github.com/doughsay/prom_ex_umbrella_example

[Router GraphQL configuration](https://files.slack.com/files-pri/T03EPRA2X-F0258LFEQPM/line.png)

**To Reproduce**
1. Add the following plugins to PromEx
2. Start application in environment 
3. Each time calling `/metric` URL it returns this

**Expected behavior**
URL should return metrics for my application

**Environment**

- Elixir version: 1.11
- Erlang/OTP version: 23
- Grafana version: v7.3.3
- Prometheus version: 2.27

**Comment by akoutmos** [comment]
Release `1.2.1` has the fix! Thanks for finding the bug and opening up the issue :)

**Comment by zmagajna** [comment]
Try it just and it works. Thanks for the quick response.
