### ISSUE TITLE
[FEATURE] Support multiple Routers in the Phoenix Plugin

### ISSUE THREAD

**Issue by emoragaf** [akoutmos/prom_ex#71]
**Is your feature request related to a problem? Please describe.**
There's no clear way of configuring the Phoenix Plugin to support multiple phoenix endpoints/routers

**Describe the solution you would like to see**
Having the option to pass a list of routers to the Plugin options.

**How would you expect this feature to work**
Having the Phoenix Plugin accept the following:

```
# keep current format for compatibility 
  {Plugins.Phoenix, router: MyApp.Router }
# current format with event_prefix
  {Plugins.Phoenix, router: MyApp.Router, event_prefix: [:custom, :prefix]}

# new format, multiple routers
  {Plugins.Phoenix, routers: [MyApp.Internal.Router, MyApp.External.Router]}
# new format, multiple routers w/ event_prefixes
  {
    Plugins.Phoenix,
    routers: [
      {MyApp.Internal.Router, event_prefix: [:custom, :prefix]},
      {MyApp.External.Router, event_prefix: [:other, :prefix]}
    ]
  }
```

**Comment by emoragaf** [comment]
Supporting multiple routers on just one Plugin it's a little more complex than I first thought.

If the router's endpoints are using all the same event_prefix is pretty straight forward, we can extend `get_conn_tags/2` to handle a list of routers to try and fetch the info.

The tricky part comes when each router endpoint has it's own `event_prefix`. Mostly because we need to listen to a different :telemetry event, so we cannot reuse the metrics definition.

The quick and simple solution that comes to mind is to include the router name in the `metric_prefix` this will allow having multiple Phoenix plugins register their own metrics without issue. But this would in turn require to pass the Router as an assign to each dashboard. @akoutmos what do you think about this?

**Comment by akoutmos** [comment]
I merged in your changes and will cut a release in the coming weeks as I have some other things that need to be in this next release. Thanks for the contribution!!
