### ISSUE TITLE
[BUG] phoenix_http_requests_total - High and Strange values

### ISSUE THREAD

**Issue by jlmartins-sf** [akoutmos/prom_ex#81]
**Describe the bug**
I add the prom_ex library to my umbrella application to collecting my metrics. And my application running inside a docker container, and my application sent these metrics I taken to my grafana/prometheus, but it seems to be a little bit odd and I don't know why. I testing replicate the example it has here in this repository, and I couldn't figure it out, and I like to know if someone can help me.

I ask because I have a scenario where Grafana is taking the total number of requests from the application in the last 24 hours, however, the local value is an unrealistic value. Checking the endpoint /metrics, I could see that the values increase every day and are not reset.

These metrics below are always with the same value, would that be correct?

app_prom_ex_phoenix_http_response_size_bytes_bucket
app_prom_ex_phoenix_http_request_duration_milliseconds_bucket
app_prom_ex_phoenix_http_request_duration_milliseconds_count
app_prom_ex_phoenix_http_requests_total
app_prom_ex_phoenix_http_response_size_bytes_count

Apparently, Grafana is adding the values every 30 seconds and adding to the counter. While in reality, I have an average of 20 thousand requests in the last 24 hours verified by Cloudflare; by Grafana, it is passing 60 million and every day, that value increases even more.

And if you need more detail let me know...

**Expected behavior**
Request values are approximated with ALB and Cloudflare.

**Environment**

- Phoenix Version: 1.5.8
- telemetry_metrics: 0.6.1
- prom_ex: 1.3.0
- Elixir version: 1.11.4
- Erlang/OTP version: 23.3.4.4
- Grafana version: 8
- Prometheus version: 2.28

**Additional context**
Grafana Dashboard Value - Last 24h:
![image](https://user-images.githubusercontent.com/79992021/126539847-13bbe64f-230b-42aa-a7b6-6d785520c564.png)

ALB AWS:
![image](https://user-images.githubusercontent.com/79992021/126543403-2e050225-5e3c-414a-b771-dd6e96112f69.png)

Metrics of application:
![image](https://user-images.githubusercontent.com/79992021/126541123-5f921a6e-66f1-4133-8928-aa057abfc5a1.png)
![image](https://user-images.githubusercontent.com/79992021/126541317-d83b819b-52b6-48ec-9f19-02d6b8129347.png)
![image](https://user-images.githubusercontent.com/79992021/126542310-039f9f8f-b533-4b2e-9988-69f2cfaec58e.png)

**Comment by akoutmos** [comment]
Thanks for opening up the issue @jlmartins-sf. That def does not seem right. I'll play around with the PromQL query today and see if I can figure out why it is so off.

**Comment by jlmartins-sf** [comment]
Thanks for the project, @akoutmos! I await your verification for this possible issue. Thank you!

**Comment by akoutmos** [comment]
Hey @jlmartins-sf! I played around with the PromQL query but forgot to respond to you -_-.

I wasn't able to see anything that would lead me to believe that the PromQL query that is feeding the dashboard is incorrect. Not that that isn't possible, but I was unable to repro and the query looks right. Is that service perhaps getting traffic behind the ALB hence the discrepancy? Any services performing healthchecks that would bump up the inbound HTTP request count?

**Comment by akoutmos** [comment]
Any additional details regarding this @jlmartins-sf?

**Comment by jlmartins-sf** [comment]
Hello, @akoutmos.
First, sorry for the delay!

I checked in my application and visualized that the metric counter is adding gradually and only resets when a new deployment is done in ECS or restarting the pod.

The resets in the chart below were the dates of the deploys that were made.
![http_requests_total_1](https://user-images.githubusercontent.com/79992021/128118502-97e41457-40cc-432b-b597-27818bb77026.png)

Grafana is running the following query:
sum(increase(core_web_prom_ex_phoenix_http_requests_total{job="$job", instance="$instance"}[24h]))

However, in this case, Grafana will take the values every 30 seconds and add them up. From what I'm checking, Prometheus is giving me the values that already summed with the result of the previous seconds, according to the graph and not the current value. Isn't that what's impacting?

And if you need more detail let me know...
Thank you, @akoutmos !!
