### ISSUE TITLE
[FEATURE] Allow using the TelemetryMetricsPrometheus built-in server

### ISSUE THREAD

**Issue by doughsay** [akoutmos/prom_ex#9]
**Is your feature request related to a problem? Please describe.**
In our deployment, we need the prometheus metrics server to be a separate server. The `TelemetryMetricsPrometheus` package provides this server for us, and we have been using it successfully.

**Describe the solution you would like to see**
A way to use the built in server provided by `TelemetryMetricsPrometheus`.

**How would you expect this feature to work**
Allow a configuration option that starts the built in server as part of the PromEx supervision tree. See here: https://hexdocs.pm/telemetry_metrics_prometheus/overview.html#getting-started

**Additional context**
I'd really like to give this library a try so as to not have to hand-roll and maintain all our own metrics.  Backing a community solution to prometheus metrics is much more appealing.

**Comment by akoutmos** [comment]
Hey Chris! I'm glad to hear that you are considering using PromEx to capture your application metrics :).

After looking at the docs for `TelemetryMetricsPrometheus`, it should actually be rather straight forward to use PromEx in conjunction with `TelemetryMetricsPrometheus` to surface metrics. I haven't given this a shot in a real application, but my hunch is that you can do something like so in your `application.ex` file:

```elixir
children = [
  {TelemetryMetricsPrometheus, [metrics: [], name: PromEx.generate_metrics_module_name(YourApp.PromEx.Module)]}
  ...
]
```

`PromEx.generate_metrics_module_name/1` is currently a hidden utility function in PromEx, and I am in the process of shifting some things around so you may not be able to count on this function in the future. But something similar should be available in the next alpha release.

Let me know if this works for you, and if it does I'll be sure to add it to the docs!

**Comment by doughsay** [comment]
Thanks for the response!  Unfortunately I don't think this works...  `TelemetryMetricsPrometheus` will try and start a process with the given name, but PromEx already started a process with that name, so it crashes on boot.

I see what you're tying to do though, we need the call to `TelemetryMetricsPrometheus.Core.scrape(name)` to pass in the right name.  Honestly, after looking through the source to `TelemetryMetricsPrometheus`, it's so small and simple I may as well just replicate it with my own needs for now.

Is TelemetryMetricsPrometheus making bad assumptions about requiring the metrics to be passed in as a list? Perhaps we just eventually include a server in PromEx for this use-case?

**Comment by doughsay** [comment]
Just as a really rough example:

```elixir
# children given to app supervisor:
[
  ...
  MyApp.PromEx,
  {Plug.Cowboy, scheme: :http, plug: MyApp.PromEx.Router, options: [port: 9568]}
]
```

```elixir
defmodule MyApp.PromEx.Router do
  @moduledoc false

  use Plug.Router

  plug :match
  plug :dispatch

  get "/metrics" do
    opts = PromEx.Plug.init(prom_ex_module: MyApp.Metrics)
    PromEx.Plug.call(conn, opts)
  end

  match _ do
    Plug.Conn.send_resp(conn, 404, "Not Found")
  end
end
```

Feels like this could be easily added to PromEx as an option (if you wanted to)

**Comment by akoutmos** [comment]
Ah I see. It uses the name for both the name of the process and the name of the metrics process to scrape. I can add a standalone server utility to PromEx. Shouldn't be a lot of work to get it in there. I'll whip something together and loop you in to see if it does what you need.

Out of curiosity, what is the motivation for running a separate server process for metrics? To have something running on a port separate from the app so that it is easier to set up network rules to block from the public internet?

**Comment by doughsay** [comment]
Yes, I think that's the main motivation. It's a requirement (or rather more of a desire) from our DevOps team. It also mimicks how all our other prometheus metrics work (e.g. ruby apps, etc.)

Also, we're building a large monolithic umbrella app (with at least a dozen separate applications), not a standard Elixir/Phoenix app. And eventually (not yet) we will be releasing and deploying just subsets of the apps instead of the whole thing as one deployment. So eventually we will have deployments that only host Oban workers for example, and won't run Phoenix themselves. So having just the lightweight plug-cowboy for cases like that make more sense than including an entire Phoenix endpoint.

**Comment by akoutmos** [comment]
Gotcha. Appreciate the insight. I'll work on something in the coming days and hope to cut a new alpha release with this added to it early next week :)

**Comment by akoutmos** [comment]
@doughsay I'm almost done with PR #10 but was wondering if you require support for `Authorization` header checks in the standalone server? Prom supports both basic and bearer token auth and I was curious if you leverage either auth strategy?

**Comment by doughsay** [comment]
Hey, thanks for all this!

We do not require any authorization checks for the standalone server.

**Comment by akoutmos** [comment]
I just cut the 0.1.7-alpha release that includes the standalone Cowboy server. If you add the following to your config it should start a separate cowboy server for you and put it under the PromEx supervisor:

```elixir
config :my_app, MyApp.PromEx,
  metrics_server: [
    port: 4021,
    path: "/metrics"
  ]
```

Take a look at the docs for more config options https://hexdocs.pm/prom_ex/0.1.7-alpha/PromEx.Config.html.

Let me know how this works out for you and your team!
