### ISSUE TITLE
[BUG] Hex dependency resolution failed with Phoenix 1.6.0

### ISSUE THREAD

**Issue by hukl** [akoutmos/prom_ex#99]
When trying to use the latest Prom_Ex with Phoenix 1.6.0 I get this dependency issue

Failed to use "telemetry_poller" (version 1.0.0) because
  prom_ex (version 1.4.1) requires ~> 0.5.1
  mix.lock specifies 1.0.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}

**Expected behavior**
Latest Prom_Ex should use latest telemetry_poller

**Comment by akoutmos** [comment]
There should be another release coming out over the next couple days :)

**Comment by cdesch** [comment]
Thanks @akoutmos ! Sounds great! I'm looking forward to it!
